<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_MhookNugetArch Condition="'$(Platform)' == 'Win32'">x86</_MhookNugetArch>
    <_MhookNugetArch Condition="'$(Platform)' == 'x64'">x64</_MhookNugetArch>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(_MhookNugetArch)' != '' and ('$(Configuration)' == 'Debug' or '$(Configuration)' == 'Release')">
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalDependencies>$(MSBuildThisFileDirectory)lib\$(_MhookNugetArch)\$(Configuration)\mhook.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
